/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import views.envn.ENVNHomeFrame;
import views.vnen.VNENHomeFrame;

/**
 *
 * @author Thien Phuc
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        this.setSize(500, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        VNENbtn = new javax.swing.JButton();
        ENVNbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Assignment 02 - CSD201");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(96, 28, 310, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Dictionary");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(199, 86, 78, 22);

        jLabel3.setText("Author: Tran Thien Phuc - SE130139");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(139, 363, 267, 16);

        VNENbtn.setText("Vietnamese - English");
        VNENbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VNENbtnActionPerformed(evt);
            }
        });
        getContentPane().add(VNENbtn);
        VNENbtn.setBounds(40, 200, 170, 25);

        ENVNbtn.setText("English - Vietnamese");
        ENVNbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENVNbtnActionPerformed(evt);
            }
        });
        getContentPane().add(ENVNbtn);
        ENVNbtn.setBounds(250, 200, 160, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VNENbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VNENbtnActionPerformed
        VNENHomeFrame frame = new VNENHomeFrame();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VNENbtnActionPerformed

    private void ENVNbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENVNbtnActionPerformed
        ENVNHomeFrame frame = new ENVNHomeFrame();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ENVNbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ENVNbtn;
    private javax.swing.JButton VNENbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
